apiVersion: v1
name: copart-harbor
version: 1.17.3
appVersion: 2.13.2
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
- copart
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/copartit/harbor-helm
maintainers:
- name: Yan Wang
  email: yan-yw.wang@broadcom.com
- name: Wenkai Yin
  email: wenkai.yin@broadcom.com
- name: Miner Yang
  email: miner.yang@broadcom.com
- name: Shengwen Yu
  email: shengwen.yu@broadcom.com
engine: gotpl
